name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build, test, and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bunx tsc
      - run: bun run build
      - run: bun run test
      - run: bun run fmt --check
      - run: bun run lint --format=github
      - uses: codecov/codecov-action@v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Publish to pkg.pr.new
        run: bunx pkg-pr-new publish --packageManager=bun,npm,pnpm --bun
